# docker-compose.green.yml
version: '3'
services:
  spring-wms-green:
    image: backend:${BUILD_NUMBER}
    container_name: spring-wms-green
    ports:
      - "8012:8080"
    environment:
      - TZ=Asia/Seoul
      - SPRING_PROFILES_ACTIVE=prod
    networks:
      - servernetwork
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  servernetwork:
    driver: bridge